### ISSUE TITLE
[Enhancement] Fullscreen

### ISSUE THREAD

**Issue by shinra358** [xan105/FFX-X2_LAUNCHER#1]
Can you make it so that the launcher is fullscreen (like the console version)?

**Comment by xan105** [comment]
I'll probably have to modify alot of things so it looks ok when fullscreen'd but it is feasible.
I'll see what i can do.

**Comment by shinra358** [comment]
cool. you can set it so that the bg of the launcher would read from a png so that the user can use their own high rez bg (considering the other topic of hiding a button). Probably wouldn't look too bad stretched either but that's up to you. Thanks again.

**Comment by xan105** [comment]
Because "copying" the original launcher style was done via picture(s) on top of each other it is not that simple to make it look good and correct while scaling. I did try to implement it in the 2.x branch but ended up removing it because it wasn't good enough. Due to lack of time and will; I have no plans for this.

**Comment by shinra358** [comment]
Old version 1.7 works just fine for me for there were many steam forum edits that were made that accomplished these things along time ago. However, I tried the new version and it reset the pic i chose to show on the title screen and im on 720p rez and I cannot navigate the menu since everything is so big and cant see the full menu. I went back to 1.7 for now
